# Generated by Django 5.2.8 on 2025-11-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_created'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amout',
            new_name='amount',
        ),
    ]
